name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Build with Make
      run: make

    - name: Install gcovr on Linux
      if: matrix.os == 'ubuntu-latest'
      run: pip install gcovr

    - name: Test with Coverage
      if: matrix.os == 'ubuntu-latest'
      run: make test

    - name: Test no Coverage
      if: matrix.os != 'ubuntu-latest'
      working-directory: ${{github.workspace}}/build
      run: |
        cmake -S .. -B . -DBUILD_TESTING=ON
        cmake --build .
        ctest --output-on-failure
